### ISSUE TITLE
Peer Review 🍐

### ISSUE THREAD

**Issue by deinca** [GiovanniKaaijk/frontend-applications#1]
Hola Gio, jouw readme is te netjes. Je legt per stap uit wat ik aan jouw project hebt want je laat zien:
- Wat voor app is je hebt gemaakt met een korte uitleg.
- Wat ik moet doen om deze repo in mijn eigen computer te installeren.
- dat je waarschuwt de lezer om eerst bepaalde stappen eerst te doen voor dat de installatie moet worden gedaan op de computer.
- dat je legt uit en laat specifieke codes om de installatie door te voeren.
- dat je ook een licentie op je app aangemaakt.

Verder zie ik dat je in je wiki een logboek hebt bijgehouden van wat je elke dag hebt gedaan. Hierdoor toont het verzorging en dat je moeite hebt gedaan om toch je proces te documenteren.

Goed gedaan !

**Comment by GiovanniKaaijk** [comment]
Thanks! :)
